SELECT * FROM AFON_IP.SRV_ATTR WHERE UP = (SELECT N FROM afon_ip.srv
WHERE UP = (SELECT N FROM AFON_IP.USR WHERE id LIKE '%776480155' AND td > SYSDATE)
AND td > SYSDATE) AND td > SYSDATE --AND ATTR = '5201';


UPDATE AFON_IP.SRV_ATTR SET VAL = 'PREPAID'
WHERE UP = (SELECT UP FROM AFON_IP.SRV_ATTR
WHERE UP = (SELECT N FROM afon_ip.srv
WHERE UP = (SELECT N FROM AFON_IP.USR
WHERE id LIKE '%776480155'
AND td > SYSDATE) AND td > SYSDATE)
AND td > SYSDATE AND ATTR = '5201')
AND ATTR = '5201';